# Generated by Django 4.2.3 on 2023-08-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmp_name', models.CharField(max_length=255)),
                ('cmp_link', models.CharField(max_length=255)),
                ('cmp_year_founded', models.CharField(max_length=255)),
                ('cmp_type', models.CharField(max_length=255)),
                ('cmp_Size_range', models.CharField(max_length=255)),
                ('cmp_location', models.CharField(max_length=255)),
                ('cmp_country', models.CharField(max_length=255)),
                ('cmp_linkedin', models.TextField()),
                ('cmp_emp_estimate', models.CharField(max_length=255)),
                ('total_cmp_emp', models.CharField(max_length=255)),
            ],
        ),
    ]
