# Generated by Django 4.2.3 on 2023-08-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userlogin',
            fields=[
                ('user_id', models.CharField(auto_created=True, max_length=255, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('user_email', models.CharField(max_length=255)),
                ('user_password', models.CharField(max_length=255)),
            ],
        ),
    ]
